lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

# api_platform:
#     authentication:
#         # Configuration spécifique à API Platform si nécessaire
#     patch_formats:
#         json: ['application/merge-patch+json']